[package]
name = "helpers"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
async-channel = "2.1"
bytemuck = { workspace = true }
futures-lite = "2.1"
png = "0.17"

[lints]
workspace = true
