[package]
name = "dunge"
description = "Simple and portable 3d render library"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
keywords = { workspace = true }
documentation = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
dunge_macros = { workspace = true }
dunge_shader = { workspace = true }
bytemuck = { workspace = true }
glam = { workspace = true }
instant = { version = "0.1", optional = true }
log = { workspace = true }
wgpu = { version = "0.18", default-features = false, features = ["naga"] }

[dependencies.winit]
version = "0.29"
default-features = false
features = ["rwh_05", "x11"]
optional = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
wgpu = { version = "0.18", default-features = false, features = ["webgl"] }

[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3"
features = ["Document", "Window", "Element", "Performance"]

[target.'cfg(target_os = "android")'.dependencies.winit]
version = "0.29"
default-features = false
features = ["android-native-activity"]
optional = true

[dev-dependencies]
helpers = { path = "../helpers" }

[features]
winit = ["dep:instant", "dep:winit"]

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc",
    "wasm32-unknown-unknown",
]
