[package]
name = "dunge"
version = "0.2.3"
edition = "2021"
description = "Simple and portable 3d render library"
license = "MIT"
keywords = ["graphics", "wgpu"]
documentation = "https://docs.rs/dunge"
readme = "../README.md"
repository = "https://github.com/nanoqsh/dunge"
rust-version = "1.71"

[dependencies]
dunge_macros = { version = "0.2.3", path = "../dunge_macros" }
dunge_shader = { version = "0.2.3", path = "../dunge_shader" }
bytemuck = { workspace = true }
glam = { workspace = true }
instant = "0.1"
log = "0.4"
wgpu = { version = "0.18", default-features = false, features = ["naga"] }

[dependencies.winit]
version = "0.29"
default-features = false
features = ["rwh_05", "x11"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
wgpu = { version = "0.18", default-features = false, features = ["webgl"] }

[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3"
features = ["Document", "Window", "Element", "Performance"]

[target.'cfg(target_os = "android")'.dependencies.winit]
version = "0.29"
default-features = false
features = ["android-native-activity"]

[dev-dependencies]
helpers = { path = "../helpers" }

[lints]
workspace = true
