[package]
name = "dunge"
version = "0.2.2"
edition = "2021"
description = "Simple and portable 3d render library"
license = "MIT"
keywords = ["graphics", "wgpu"]
documentation = "https://docs.rs/dunge"
readme = "../README.md"
repository = "https://github.com/nanoqsh/dunge"
rust-version = "1.71"

[dependencies]
dunge_macros = "0.2"
dunge_shader = "0.2"
bytemuck = { version = "1.13", features = ["derive"] }
glam = "0.24"
instant = "0.1"
log = "0.4"
wgpu = "0.18"
winit = { version = "0.29", default-features = false, features = ["rwh_05"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
wgpu = { version = "0.18", features = ["webgl"] }
web-sys = { version = "0.3", features = [
    "Document",
    "Window",
    "Element",
    "Performance",
] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pollster = "0.3"

[target.'cfg(target_os = "android")'.dependencies]
winit = { version = "0.29", default-features = false, features = [
    "android-native-activity",
] }

[features]
default = ["x11"]
x11 = ["winit/x11"]
wayland = ["winit/wayland"]
