[package]
name = "dunge"
version = "0.1.6"
edition = "2021"
description = "Simple and portable 3d render library"
license = "MIT"
keywords = ["graphics", "wgpu"]
documentation = "https://docs.rs/dunge"
readme = "../README.md"
repository = "https://github.com/nanoqsh/dunge"
rust-version = "1.67"

[dependencies]
ahash = "0.8"
log = "0.4"
once_cell = "1.17"
wgpu = "0.15"
winit = { version = "0.28", default-features = false }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
wgpu = { version = "0.15", features = ["webgl"] }
web-sys = { version = "0.3", features = ["Document", "Window", "Element", "Performance"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pollster = "0.2"

[target.'cfg(target_os = "android")'.dependencies]
ndk-glue = { version = "0.7", features = ["logger"] }

[target.'cfg(target_os = "linux")'.dependencies]
winit = { version = "0.28", default-features = false, features = ["x11"] }
