[package]
name = "window"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
dunge = { workspace = true, features = ["winit"] }
env_logger.workspace = true

[lints]
workspace = true
