[package]
name = "window"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
dunge_winit.workspace = true
env_logger.workspace = true
futures-concurrency.workspace = true
futures-lite.workspace = true
winit.workspace = true

[lints]
workspace = true
