[package]
name = "dunge"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.7"
glam = "0.21"
log = "0.4"
pollster = "0.2"
wgpu = "0.14"
winit = "0.27"

[dev-dependencies]
env_logger = "0.9"
image = { version = "0.24", default-features = false, features = ["png"] }

[[example]]
name = "cube"
