[workspace]
members = ["dunge", "dunge_macros", "dunge_shader", "helpers"]
resolver = "2"

[workspace.dependencies]
bytemuck = "1.13"
glam = "0.25"

[workspace.lints.clippy]
use-self = "deny"
unwrap-used = "deny"
missing-assert-message = "deny"
match-wildcard-for-single-variants = "deny"
flat-map-option = "deny"
semicolon-if-nothing-returned = "deny"
manual-assert = "deny"
needless-pass-by-value = "deny"
trivially-copy-pass-by-ref = "deny"

[profile.dev]
opt-level = 1
panic = "abort"
split-debuginfo = "unpacked"

[profile.dev.package."*"]
opt-level = 3

[profile.ci]
inherits = "dev"
opt-level = 1

[profile.ci.package."*"]
opt-level = 1

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true
