[package]
name = "dunge_shader"
version = "0.2.3"
edition = "2021"
description = "Shader generator for the dunge library"
license = "MIT"
documentation = "https://docs.rs/dunge"
repository = "https://github.com/nanoqsh/dunge"

[dependencies]
naga = "0.14"

[lints]
workspace = true
