[package]
name = "xtask"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
askama = { workspace = true, features = ["derive", "std"] }
helpers = { workspace = true, features = ["serv"] }

[lints]
workspace = true
