[package]
name = "serv_wasm"
version = "0.1.0"
edition = { workspace = true }
publish = false

[dependencies]
askama = { version = "0.12", default-features = false }
helpers = { path = "../../helpers", features = ["serv"] }

[lints]
workspace = true
