[build]
# target = "wasm32-unknown-unknown"
rustflags = ["--cfg=web_sys_unstable_apis"]
rustdocflags = ["--cfg=web_sys_unstable_apis"]

[alias]
xtask = "run --package xtask --"
x = "run --package xtask --"
