[package]
name = "scene"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "scene_bin"
path = "src/main.rs"

[dependencies]
dunge = { path = "../../dunge" }
utils = { path = "../utils" }
env_logger = "0.9"
