[package]
name = "triangle"
version = "0.1.0"
edition.workspace = true
publish = false

[[bin]]
name = "triangle_bin"
path = "src/main.rs"

[dependencies]
dunge_winit.workspace = true
env_logger.workspace = true
futures-concurrency.workspace = true
winit.workspace = true

[lints]
workspace = true
