[package]
name = "window2"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
dunge.workspace = true
dunge_winit.workspace = true
env_logger.workspace = true
futures-lite.workspace = true
helpers.path = "../../helpers"

[lints]
workspace = true
